exclude: "vendor/.*"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-private-key
      - id: mixed-line-ending
      - id: fix-byte-order-marker

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.3
    hooks:
      - id: clang-format
        files: 'src/.*'
