name: Dev tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  build:
    name: Build
    runs-on: windows-2019
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,Kalak,read;nugettimeout,3600'
      VCPKG_USE_NUGET_CACHE: 1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup vcpkg
        run: .\vcpkg\bootstrap-vcpkg
      - name: Setup nuget
        run: nuget sources add -source ${{ secrets.NUGET_REPO_URL }} -name Kalak
      - run: mkdir build
      - name: CMake
        run: cmake -S . -B ./build "-DCMAKE_TOOLCHAIN_FILE=$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake"
      - name: Build
        run: cmake --build .\build\ --config Release
