name: Dev tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  build:

    name: Build

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            mono: ''
            nuget: 'nuget'
            preset: 'x64-win-min-vs2022-rel'
          - os: ubuntu-latest
            mono: 'mono'
            nuget: '`./vcpkg/vcpkg fetch nuget | tail -n 1`'
            preset: 'x64-linux-min-gcc-rel'

    runs-on: ${{ matrix.os }}
    
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,Kalak,readwrite;nugettimeout,3600'
      VCPKG_USE_NUGET_CACHE: 1
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Generate presets
        run: python ./config/presets/generate.py
      - name: Setup vcpkg
        run: ./vcpkg/bootstrap-vcpkg
      - name: Setup nuget
        run: >
          ${{ matrix.mono }} ${{ matrix.nuget }} sources add
          -source ${{ secrets.NUGET_REPO_URL }}
          -name Kalak
          -storepasswordincleartext
          -username ${{ secrets.NUGET_REPO_USER }}
          -password ${{ secrets.NUGET_REPO_PASS }}
      - run: mkdir build
      - name: CMake
        run: cmake --preset ${{ matrix.preset }}
      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}
