name: Dev tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  build:
    name: Build
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,Kalak,readwrite;nugettimeout,3600'
      VCPKG_USE_NUGET_CACHE: 1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Generate presets
        run: python .\config\presets\generate.py
      - name: Setup vcpkg
        run: .\vcpkg\bootstrap-vcpkg
      - name: Setup nuget
        run: >
          nuget sources add
          -source ${{ secrets.NUGET_REPO_URL }}
          -name Kalak
          -storepasswordincleartext
          -username ${{ secrets.NUGET_REPO_USER }}
          -password ${{ secrets.NUGET_REPO_PASS }}
      - run: mkdir build
      - name: CMake
        run: cmake --preset x64-win-min-vs2022-rel
      - name: Build
        run: cmake --build --preset x64-win-min-vs2022-rel
