name: Pre-master tests
on:
  pull_request:
    branches:
      - master
jobs:

  check-version:
    name: Check version updated
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - id: get-master-version
        run: |
          echo "::set-output name=master-ver::$(grep -Ps "^#define TINYC_VERSION.* (\d+)$" src/tcc/version/Version.h | grep -Po "\d+" | xargs | tr ' ' '.' | sed "s/^/v/g")"
      - uses: actions/checkout@v3
      - id: get-dev-version
        run: |
          echo "::set-output name=dev-ver::$(grep -Ps "^#define TINYC_VERSION.* (\d+)$" src/tcc/version/Version.h | grep -Po "\d+" | xargs | tr ' ' '.' | sed "s/^/v/g")"
      - name: Versions are same
        if: ${{ steps.get-master-version.outputs.master-ver == steps.get-dev-version.outputs.dev-ver }}
        uses: actions/github-script@v3
        with:
          script: core.setFailed('master and dev versions are equal -- update in src/tcc/version/Version.h')
