name: Test
on: [push]
jobs:

  list-examples:
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find examples -iname "*.c" -exec sh -c 'printf "%s\n" "${0%.*}"' {} ';' | jq -R -s -c 'split("\n")[:-1]')"

  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build
      - name: Cmake
        working-directory: ./build
        run: cmake ..
      - name: Build
        working-directory: ./build
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: tcc-exe
          path: build/tcc

  test:
    needs: [list-examples, build]
    name: Test
    runs-on: self-hosted
    strategy:
      matrix:
        example: ${{ fromJson(needs.list-examples.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: tcc-exe
      - run: ls
      - name: Translate to IR
        run: ./tcc '${{ matrix.example }}.c'
      - name: Translate to ASM
        run: llc -opaque-pointers '${{ matrix.example }}.ll'
      - name: Compile
        run: gcc '${{ matrix.example }}.s' -o ${{ matrix.example }}
      - name: Run example
        run: ${{ matrix.example }}
